# Generated by Django 3.2.9 on 2021-11-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='uniqueid',
        ),
    ]
