# Generated by Django 3.2.9 on 2021-11-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_certificate_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='certificates/')),
            ],
        ),
    ]
