# Generated by Django 3.2.9 on 2021-11-25 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_certificatetemplates_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplates',
            name='file',
            field=models.FileField(upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['html'])]),
        ),
    ]
