# Generated by Django 3.2.9 on 2021-11-25 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_certificatetemplates_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_template',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.certificatetemplates'),
            preserve_default=False,
        ),
    ]
